In [15]:
L = [10,20,30]
W=L
L.append(40)
print(W)

[10, 20, 30, 40]


In [16]:
L = L + [60]

print(W)

[10, 20, 30, 40]


In [17]:
# L = [10]
# for e in L:    #infinite loop
#     L.append(e)
# print(L)

Comprehension:
Can be done also with `map` function:

In [18]:
squares1 = list(map(lambda x: x**2, range(10)))

In [ ]:
squares2 = [x**2 for x in range(10)]
print(squares1==squares2)

In [ ]:
L = [10]
for e in L:
    L = L + [e]
print(L)

Given a unary function $f$ and a sequence S, return the list of the application of f to the element of S

In [ ]:
def image_f_through_S(f,S):
    return [f(s) for s in S]
S = [1,2,3,4]

I = image_f_through_S(lambda x: x**2,S)
print(I)

Given two sequences S1 and S2 return the list of the elements present in both S1 and S2 (don't bother about multiplicity: if e appears in both S1 and S2, maybe many times in S1, or in S2, or in both, it may appear with whatever multiplicity in the result)

In [ ]:
S1 = [1,2,3,4,5,6,7,7,8]
S2 = [5,454,6,4,6,7,2,1,23]

# S = [x for x in S1 if x in S2 ]
S = [x for x in S2 if x in S1 ]
S

Pythagorean triples: $(a,b,c)$ such that $a^2+b^2=c^2$, for $a+b+c \le k$

In [ ]:
def pitagorean_triples(k):
    return [(a,b,c) for a in range(1,k) for b in range(1,k) for c in range(1,k)  if a+b+c <= k if a**2+b**2 -c**2 == 0]
pitagorean_triples(30)

Return the list of all the permutations of the elements of L; does not modify L

In [ ]:
# auxiliary function removing an element from L and returning the shrunk list
def erase(e,L):
    if e in L:
        return [l for l in L if l != e]
    else:
        return ValueError

# non-scalable solution
def perm3(L):
  return [[a,b,c] for a in L for b in erase(a,L)  for c in erase(b,erase(a,L))]

perm3([1,2,3])

The permutations of L are obtained by taking as first element, any element of L, and taking then all the permutations of the remaining elements recursively.

In [25]:
def perm(L):
    if len(L) == 0:
        return [[]]

    return [[l] + p for l in L for p in perm(erase(l,L))]

# Example usage:
my_list = [1, 2, 3, 4]
result = perm(my_list)
print(result)

[[1, 2, 3, 4], [1, 2, 4, 3], [1, 3, 2, 4], [1, 3, 4, 2], [1, 4, 2, 3], [1, 4, 3, 2], [2, 1, 3, 4], [2, 1, 4, 3], [2, 3, 1, 4], [2, 3, 4, 1], [2, 4, 1, 3], [2, 4, 3, 1], [3, 1, 2, 4], [3, 1, 4, 2], [3, 2, 1, 4], [3, 2, 4, 1], [3, 4, 1, 2], [3, 4, 2, 1], [4, 1, 2, 3], [4, 1, 3, 2], [4, 2, 1, 3], [4, 2, 3, 1], [4, 3, 1, 2], [4, 3, 2, 1]]


In [26]:
# seasons = ['Spring', 'Summer', 'Fall', 'Winter']
# list(enumerate(seasons,start=3))

In [27]:
# def compare(s1,s2):
#     return tuple(i for i, c in enumerate(s1) if c in s2[max(0, i - 1):min(i + 2, len(s2))])


In [18]:
# Unicode code points of the alphabet
# lexicographical order checked by comparison operators through this code
s = 'abcdefghilmnopqrstuvwxyz'
for c in s:
    C = c.upper()
    print(c, ord(c), C, ord(C), sep='  ')    

False
a  97  A  65
b  98  B  66
c  99  C  67
d  100  D  68
e  101  E  69
f  102  F  70
g  103  G  71
h  104  H  72
i  105  I  73
l  108  L  76
m  109  M  77
n  110  N  78
o  111  O  79
p  112  P  80
q  113  Q  81
r  114  R  82
s  115  S  83
t  116  T  84
u  117  U  85
v  118  V  86
w  119  W  87
x  120  X  88
y  121  Y  89
z  122  Z  90


In [ ]:
'''L: ordered list, in increasing order; insert el in L, in place'''
def ins_ord(L,el): 
    # linear search
    i=0
    while i<len(L) and L[i]<el:
        i = i+1
    L.insert(i,el)  # equivalent: L[i:i]=[el]
    return L

def ins_ord_b(L,el):
    # binary search
    low=0
    high=len(L)
    while low<high:
        med=(low+high)//2
        if L[med]>el:
            high=med
        else:
            low=med+1
    L.insert(high,el)  # equivalent: L[high:high]=[el]
    return L
'''An inefficent solution:
it solved the problem, but it costs more than the others.
It append the element, then re-sort the list.
Sorting costs more than a single scan of the list'''
def ins_ord_L(L,el):
    L.append(el)
    L.sort()
    return None

In [60]:
# Floyd triangle
def print_row(low, high):
    while low < high+1:
        print(low, end=' ')
        low +=1
    print('\n')
    
def floyd(n):
    i = 1
    max = 1
    curr_ord = 1
    while max <= n*(n+1)/2:
        print_row(i,max)
        i = max +1
        max += curr_ord +1
        curr_ord +=1
floyd(5)

1 

2 3 

4 5 6 

7 8 9 10 

11 12 13 14 15 


## Matrices
Here a matrix is encoded as a built-in list where indeces start from zero


In [100]:
def is_sum_mat(A,B,S):
    n_rows = len(A)
    n_cols = len(A[0])
    # A,B,S encoded as lists
    # verify that S[i][j] = A[i][j] + B[i][j]
    for i in range(n_rows): # rows
        for j in range(n_cols): # cols
            if S[i][j] != A[i][j] + B[i][j]:
                return False
    return True
def sum_mat(A,B):
    n_rows = len(A)
    n_cols = len(A[0])
    return [[A[i][j]+B[i][j] for j in range(n_cols)] for i in range(n_rows)]
   
A = [[7,9],
     [5,3],
     [1,2]]
B = [[1,3],
     [-5,-3],
     [-9,3]]
S = [[8,12],
     [0,0],
     [-8,5]]
print(is_sum_mat(A,B,S))
S = sum_mat(A,B)
print(S)

True
[[8, 12], [0, 0], [-8, 5]]


In [102]:
def transp(A):
    n_rows = len(A)
    n_cols = len(A[0])
    return [[A[j][i] for j in range(n_rows)] for i in range(n_cols)]

A = [[7,9],
     [5,3],
     [1,2]]
print(transp(A))

[[7, 5, 1], [9, 3, 2]]


In [103]:
# scalar (dot) product
def dot_prod(x,y):
    # x and y are two lists of the same length
    return sum([x[i]*y[i] for i in range(len(x))])

x = [1,2,3]
y = [1,2,3]
print(dot_prod(x,y))

14


 Dot product between two matrices $A$ and $B$ (where the n_cols of $A$ is equal to n_rows of $B$ to be compatible) can be seen as the dot product of
the rows of $A$ and the rows of $B^T$.

In [113]:
# dot product between two matrices
def dot_prod_mat(A,B):
    return [[dot_prod(x,y) for y in transp(B)] for x in A ]


A1 = [[7,9],
     [5,3],
     [1,2]]
A2 = [[1,3,1],
     [-5,-3,1]]
import numpy as np
A1_arr = np.array(A1)
A2_arr = np.array(A2)
print('with numpy: ',A1_arr@A2_arr,sep='\n')
print(dot_prod_mat(A1,A2))

with numpy: 
[[-38  -6  16]
 [-10   6   8]
 [ -9  -3   3]]
[[-38, -6, 16], [-10, 6, 8], [-9, -3, 3]]
